/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package pokegym

import kotlin.test.Test
import kotlin.test.assertNotNull

class PokegymApplicationTest {
    @Test fun testAppHasAGreeting() {
        val classUnderTest = PokegymApplication()
        assertNotNull(classUnderTest.name, "app should have a greeting")
    }
}
